service: puppeteer-lambda-starter-kit

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 1536
  timeout: 180

functions:
  test-function:
    handler: index.handler

package:
  artifact: ./package.zip
  
plugins:
  - serverless-hooks-plugin

custom:
  hooks:
    package:initialize:
      - npm run package